### ISSUE TITLE
requirements.txt seems off

### ISSUE THREAD

**Issue by zg-alexey** [TheAhmadOsman/4o-ghibli-at-home#3]
Trying latest main branch. Conda + python 3.11.
Installing requirements.txt packages fails:
```
Collecting nvidia-cufft-cu12==11.3.0.4 (from -r requirements.txt (line 40))
  Using cached nvidia_cufft_cu12-11.3.0.4-py3-none-win_amd64.whl.metadata (1.5 kB)
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-cufile-cu12==1.11.1.6 (from versions: none)
ERROR: No matching distribution found for nvidia-cufile-cu12==1.11.1.6
```
Looks like requirements.txt have a version of a package requiring python<3.11, but if I try 3.10 - it is the similar issue with other package requiring python >=3.11. Plus - I see you mention 3.11 in docs.

**Comment by TheAhmadOsman** [comment]
I just tried running the project in a new Python 3.11 venv with `uv` and it worked flawlessly as seen in the below screenshot. Please try using `uv` and let me know how that goes.

![Image](https://github.com/user-attachments/assets/b1cd3a7f-0e2f-439b-b985-cb32a9e0ebc5)

**Comment by zg-alexey** [comment]
Sure, tried with uv, still similar issue:

![Image](https://github.com/user-attachments/assets/94426436-5304-4197-afe5-82d4903129dc)

**Comment by TheAhmadOsman** [comment]
Yeah, unfortunately I am not sure if this would work on Windows. You could maybe try a VM with a GPU passthrough?

**Comment by zg-alexey** [comment]
Ah. Ok. I've seen windows mentioned in readme, so assumed it should work there as well. 
I am not sure GPU passthrough will work on my configuration, so instead I'll try coming up with compatible set of packages for windows instead, 
I quite assume it is just a question of finding right versions/already built wheels, as I have quite a lot of different AI apps here, and none of them had such issues when installing. When I'll have it working - I'll share requirements.txt that works.

**Comment by aa956** [comment]
By the way, it may be a good idea to update README.md, `uv venv` command in the README does not include python version and installs 3.12 for me (on debian trixie but this is probably irrelevant):

```console
$ uv venv --python 3.11
```

**Comment by TheAhmadOsman** [comment]
> By the way, it may be a good idea to update README.md, `uv venv` command in the README does not include python version and installs 3.12 for me (on debian trixie but this is probably irrelevant):
> 
> $ uv venv --python 3.11

Done


> Okay, after reading this thread, it seems that this does not work on Windows 11 out of the box. Thanks!

I have it on the roadmap to get this done ASAP

**Comment by zg-alexey** [comment]
I made it work on win10 (and, I suppose, on win11 as well).
Here is requirements.txt for it. Basically - remove all nvidia* packages, those don't exist for win. Also remove triton (for now, but there's a build for win, just not accessible directly through pip, I'll address it later). 
Then - install torch with cuda support like this - uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
Tweak path to fit your cuda version. Mine is 12.8
After that the app will start. Almost. As there's unrelated issue of app not being able to download a model, as it is gated.
You need to change this line of code and provide huggingface token to be able to download it.
```
 pipe = FluxKontextPipeline.from_pretrained(
        "black-forest-labs/FLUX.1-Kontext-dev", torch_dtype=TORCH_DTYPE, token="hf_#######################"
    )
```
After that - it works :)

[requirements.txt](https://github.com/user-attachments/files/21059487/requirements.txt)

**Comment by TheAhmadOsman** [comment]
@zg-alexey hey, do you mind trying a brand new venv on Windows using the new `pyproject.toml`? Hopefully that should fix it for the Windows folks

Let me know

**Comment by zg-alexey** [comment]
> [@zg-alexey](https://github.com/zg-alexey) hey, do you mind trying a brand new venv on Windows using the new `pyproject.toml`? Hopefully that should fix it for the Windows folks
> 
> Let me know

Tried with new venv, python 3.12 and uv sync command. Packages installed correctly. But it has installed torch without cuda support, making it run on CPU. 
So I still have to run this command to be able to have GPU support:
` uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`
